os: linux
language: go
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
# sudo: requried
dist: trusty

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on
    - REGISTRY_USER=${REGISTRY_USER}
    - REGISTRY_PASS=${REGISTRY_PASS}
    - secure: "${REGISTRY_SECURE}"
  jobs:
    include:
      - arch: ppc64le
        TARGET=amd64
        

before_install:
  - sudo apt-get update -qq
  - go get github.com/mattn/goveralls

install:
  - go get -u golang.org/x/lint/golint

before_script:
  # Make gopath... to run golint/go fmt/go vet
  # Suppress golint for fixing lint later.
  - golint ./... | grep -v vendor | grep -v ALL_CAPS | xargs -r false
  - go fmt ./...
  - go vet ./...
#  - gocyclo -over 15 ./multus

script:
  - GOARCH="${TARGET}" ./build
  - |
    if [ "${TARGET}" == "amd64" ]; then
      sudo env PATH=${PATH} ./test.sh
      goveralls -coverprofile=coverage.out -service=travis-ci
      docker build -t nfvpe/multus:latest-amd64 .
      docker build -t nfvpe/multus:latest-ppc64le -f Dockerfile.ppc64le .
      docker build -t nfvpe/multus-origin:latest -f Dockerfile.openshift .
    fi

